### ISSUE TITLE
Update Bluetooth guides for Raspbian with Pixel

### ISSUE THREAD

**Issue by ArthurZC23** [ricardozago/NoVo-Pi#12]
Just do the GUI version. Don't need the bash version. @ricardozago

**Comment by ricardozago** [comment]
Arthur, bluetooth procedure to connect don't changed. Or you wanna update because window theme?

**Comment by ArthurZC23** [comment]
It is the same thing? Then never mind, leave the way it is. Thank you.

2016-10-21 23:45 GMT-02:00 Ricardo Zago <notifications@github.com>:
